Minor updates and fixes.

diff --git a/cmappertools/configure b/cmappertools/configure
--- a/cmappertools/configure
+++ b/cmappertools/configure
@@ -15460,9 +15460,20 @@ $as_echo_n "checking for boostlib >= $boost_lib_version_req... " >&6; }
 
                         libsubdirs="lib"
     ax_arch=`uname -m`
-    if test $ax_arch = x86_64 -o $ax_arch = ppc64 -o $ax_arch = s390x -o $ax_arch = sparc64; then
+    case $ax_arch in
+      x86_64|ppc64|s390x|sparc64|aarch64)
         libsubdirs="lib64 lib lib64"
-    fi
+        ;;
+    esac
+
+
+    libsubdirs="lib/${host_cpu}-${host_os} $libsubdirs"
+
+    case ${host_cpu} in
+      i?86)
+        libsubdirs="lib/i386-${host_os} $libsubdirs"
+        ;;
+    esac
 
                 if test "$ac_boost_path" != ""; then
         BOOST_CPPFLAGS="-I$ac_boost_path/include"
@@ -15655,7 +15666,7 @@ $as_echo "$as_me: We could not detect the boost libraries (version $boost_lib_ve
 $as_echo "$as_me: Your boost libraries seems to old (version $_version)." >&6;}
         fi
         # execute ACTION-IF-NOT-FOUND (if present):
-        echo 'Warning: Path to Boost libraries was not found. Try setting the BOOST_ROOT environment variable.'
+        echo 'Warning: Path to Boost libraries was not found. Please install Boost, or try setting the BOOST_ROOT environment variable if Boost is already installed and the script could not find it.'; exit 1
     else
 
 
@@ -16189,62 +16200,7 @@ fi
 extra_compile_args="$BOOST_CPPFLAGS"
 extra_link_args="$BOOST_LDFLAGS $BOOST_THREAD_LIB $BOOST_CHRONO_LIB"
 
-{ $as_echo "$as_me:${as_lineno-$LINENO}: checking whether C++ compiler accepts " >&5
-$as_echo_n "checking whether C++ compiler accepts ... " >&6; }
-if ${ax_cv_check_cxxflags__+:} false; then :
-  $as_echo_n "(cached) " >&6
-else
 
-  ax_check_save_flags=$CXXFLAGS
-  CXXFLAGS="$CXXFLAGS  "
-  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
-/* end confdefs.h.  */
-
-int
-main ()
-{
-
-  ;
-  return 0;
-}
-_ACEOF
-if ac_fn_cxx_try_compile "$LINENO"; then :
-  ax_cv_check_cxxflags__=yes
-else
-  ax_cv_check_cxxflags__=no
-fi
-rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
-  CXXFLAGS=$ax_check_save_flags
-fi
-{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ax_cv_check_cxxflags__" >&5
-$as_echo "$ax_cv_check_cxxflags__" >&6; }
-if test x"$ax_cv_check_cxxflags__" = xyes; then :
-  :
-else
-  :
-fi
-
-if ${CXXFLAGS+:} false; then :
-  case " $CXXFLAGS " in
-    *"  "*)
-      { { $as_echo "$as_me:${as_lineno-$LINENO}: : CXXFLAGS already contains "; } >&5
-  (: CXXFLAGS already contains ) 2>&5
-  ac_status=$?
-  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
-  test $ac_status = 0; }
-      ;;
-    *)
-      { { $as_echo "$as_me:${as_lineno-$LINENO}: : CXXFLAGS=\"\$CXXFLAGS \""; } >&5
-  (: CXXFLAGS="$CXXFLAGS ") 2>&5
-  ac_status=$?
-  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
-  test $ac_status = 0; }
-      CXXFLAGS="$CXXFLAGS "
-      ;;
-   esac
-else
-  CXXFLAGS=""
-fi
 
 
 
@@ -16310,41 +16266,7 @@ fi
 done
 
 
-{ $as_echo "$as_me:${as_lineno-$LINENO}: checking whether the linker accepts " >&5
-$as_echo_n "checking whether the linker accepts ... " >&6; }
-if ${ax_cv_check_ldflags__+:} false; then :
-  $as_echo_n "(cached) " >&6
-else
 
-  ax_check_save_flags=$LDFLAGS
-  LDFLAGS="$LDFLAGS  "
-  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
-/* end confdefs.h.  */
-
-int
-main ()
-{
-
-  ;
-  return 0;
-}
-_ACEOF
-if ac_fn_cxx_try_link "$LINENO"; then :
-  ax_cv_check_ldflags__=yes
-else
-  ax_cv_check_ldflags__=no
-fi
-rm -f core conftest.err conftest.$ac_objext \
-    conftest$ac_exeext conftest.$ac_ext
-  LDFLAGS=$ax_check_save_flags
-fi
-{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ax_cv_check_ldflags__" >&5
-$as_echo "$ax_cv_check_ldflags__" >&6; }
-if test x"$ax_cv_check_ldflags__" = xyes; then :
-  :
-else
-  :
-fi
 
 
 
